/oak:
  ros__parameters:
    camera:
      i_nn_type: rgb
      i_pipeline_type: rgb
    stereo:
      i_subpixel: true
    imu:
      i_enable_rotation: false
      i_message_type: IMU_WITH_MAG
    nn:
      i_nn_config_path: depthai_ros_driver/segmentation
      i_enable_passthrough: true